title: FC Modelling
description: Quantitative football modelling, predictive betting markets insights
theme: jekyll-theme-minimal
markdown: kramdown
exclude:
  - code
  - venv
  - requirements.txt
  - README.md